import { db } from '@/db';
import { anime } from '@/db/schema';

async function main() {
    const sampleAnime = [
        {
            slug: 'demon-slayer-kimetsu-no-yaiba',
            title: 'Demon Slayer: Kimetsu no Yaiba',
            japaneseTitle: '鬼滅の刃',
            synopsis: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
            coverImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200',
            rating: 8.9,
            genres: ['Action', 'Adventure', 'Supernatural', 'Drama'],
            status: 'completed',
            releaseYear: 2019,
            totalEpisodes: 26,
            type: 'Series',
            trending: true,
            mostWatched: true,
            pinned: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            slug: 'attack-on-titan',
            title: 'Attack on Titan',
            japaneseTitle: '進撃の巨人',
            synopsis: 'Humanity lives inside cities surrounded by enormous walls that protect them from gigantic man-eating humanoids referred to as Titans. The story follows Eren Yeager, who vows to retake the world after a Titan brings about the destruction of his hometown.',
            coverImage: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=1200',
            rating: 9.1,
            genres: ['Action', 'Drama', 'Fantasy', 'Mystery'],
            status: 'completed',
            releaseYear: 2013,
            totalEpisodes: 25,
            type: 'Series',
            trending: true,
            mostWatched: true,
            pinned: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            slug: 'my-hero-academia',
            title: 'My Hero Academia',
            japaneseTitle: '僕のヒーローアカデミア',
            synopsis: 'In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that will not stop him from enrolling in a prestigious hero academy.',
            coverImage: 'https://images.unsplash.com/photo-1601513446506-9b98e9a6d10f?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1601513446506-9b98e9a6d10f?w=1200',
            rating: 8.7,
            genres: ['Action', 'Comedy', 'School', 'Shounen'],
            status: 'ongoing',
            releaseYear: 2016,
            totalEpisodes: 13,
            type: 'Series',
            trending: true,
            mostWatched: false,
            pinned: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            slug: 'jujutsu-kaisen',
            title: 'Jujutsu Kaisen',
            japaneseTitle: '呪術廻戦',
            synopsis: 'A boy swallows a cursed talisman and becomes host to a powerful curse. He joins a secret organization of Jujutsu Sorcerers in order to kill the powerful curse that now lives inside him.',
            coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200',
            rating: 8.8,
            genres: ['Action', 'Supernatural', 'School', 'Shounen'],
            status: 'ongoing',
            releaseYear: 2020,
            totalEpisodes: 24,
            type: 'Series',
            trending: true,
            mostWatched: true,
            pinned: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            slug: 'one-piece',
            title: 'One Piece',
            japaneseTitle: 'ワンピース',
            synopsis: 'Monkey D. Luffy sets off on an adventure with his pirate crew in hopes of finding the greatest treasure ever, known as the "One Piece." Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line.',
            coverImage: 'https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=1200',
            rating: 8.9,
            genres: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
            status: 'ongoing',
            releaseYear: 1999,
            totalEpisodes: 1000,
            type: 'Series',
            trending: false,
            mostWatched: false,
            pinned: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            slug: 'naruto-shippuden',
            title: 'Naruto Shippuden',
            japaneseTitle: 'ナルト疾風伝',
            synopsis: 'Naruto Uzumaki returns from training with a mission: to save his friend Sasuke Uchiha from the grips of the snake-like shinobi, Orochimaru. But when he fails, Naruto must train harder than ever to protect his village and friends.',
            coverImage: 'https://images.unsplash.com/photo-1620121478247-ec786b9be2fa?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1620121478247-ec786b9be2fa?w=1200',
            rating: 8.6,
            genres: ['Action', 'Adventure', 'Martial Arts', 'Shounen'],
            status: 'completed',
            releaseYear: 2007,
            totalEpisodes: 500,
            type: 'Series',
            trending: false,
            mostWatched: false,
            pinned: false,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            slug: 'chainsaw-man',
            title: 'Chainsaw Man',
            japaneseTitle: 'チェンソーマン',
            synopsis: 'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita.',
            coverImage: 'https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=1200',
            rating: 8.7,
            genres: ['Action', 'Comedy', 'Supernatural', 'Gore'],
            status: 'completed',
            releaseYear: 2022,
            totalEpisodes: 12,
            type: 'Series',
            trending: false,
            mostWatched: false,
            pinned: false,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            slug: 'spy-x-family',
            title: 'Spy x Family',
            japaneseTitle: 'スパイファミリー',
            synopsis: 'A spy on an undercover mission gets married and adopts a child as part of his cover. His wife and daughter have secrets of their own, and all three must hide their true identities even as they come to genuinely care about each other.',
            coverImage: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=400',
            bannerImage: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=1200',
            rating: 9.0,
            genres: ['Action', 'Comedy', 'Slice of Life', 'Shounen'],
            status: 'ongoing',
            releaseYear: 2022,
            totalEpisodes: 12,
            type: 'Movie',
            trending: false,
            mostWatched: false,
            pinned: false,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
    ];

    await db.insert(anime).values(sampleAnime);
    
    console.log('✅ Anime seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});